import sqlite3

database = sqlite3.connect("AntikytheraSystem.db")
cursor = database.cursor()

sql_command = """CREATE TABLE IF NOT EXISTS Planets (
NAME TEXT NOT NULL PRIMARY KEY,
RADIUS INTEGER NOT NULL,
MASS INTEGER NOT NULL,
PLANET_TYPE TEXT NOT NULL,
GRAVITATIONAL_PULL INTEGER NOT NULL,
AVG_SURFACE_TEMP INTEGER NOT NULL,
DISTANCE_TO_SUN INTEGER NOT NULL,
ORBITAL_POSITION TEXT NOT NULL,
NUMBER_OF_MOONS INTEGER NOT NULL,
ORBITAL_PERIOD INTEGER NOT NULL)
;"""

cursor.execute(sql_command)

sql_command = """CREATE TABLE IF NOT EXISTS Moons(
NAME TEXT NOT NULL PRIMARY KEY,
RADIUS INTEGER NOT NULL,
MASS INTEGER NOT NULL,
GRAVITATIONAL_PULL INTEGER NOT NULL,
ORBITAL_POSITION TEXT NOT NULL,
ORBITED_PLANET TEXT NOT NULL)
;"""

cursor.execute(sql_command)

sql_command = """CREATE TABLE IF NOT EXISTS Small_Bodies(
NAME TEXT NOT NULL PRIMARY KEY,
TYPE TEXT NOT NULL,
POSITION TEXT NOT NULL,
SIZE INTEGER NOT NULL,
SPEED INTEGER NOT NULL)
;"""

cursor.execute(sql_command)

sql_command = """CREATE TABLE IF NOT EXISTS Eclipses(
TYPE TEXT NOT NULL,
DATE TEXT NOT NULL PRIMARY KEY,
LOCATION TEXT NOT NULL)
;"""

cursor.execute(sql_command)

sql_command = """CREATE TABLE IF NOT EXISTS Zodiac_Constellations(
NAME TEXT NOT NULL PRIMARY KEY,
DATE_START TEXT NOT NULL,
DATE_END TEXT NOT NULL)
;"""

cursor.execute(sql_command)
